#include <SFML/Graphics.hpp>

using namespace sf;

const int H = 23;
const int W = 53;


String TileMap[H] = {
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"B                          0  0 0B     BBBBBBBBBBBBB",
"B                                B     BBBBBBBBBBBBB",
"B0                               B    0  XBBBBBBBBBB",
"B                                B       LBBBBBBBBBB",
"B                     BB         B     BBBBBBBBBBBBB",
"B0                    BB      0  B0    BBBBBBBBBBBBB",
"BBB     BBB           BB      BBBBB    BBBBBBBBBBBBB",
"B              BB     BB     BB       BBBBBBBBBBBBBB",
"B    0         BB     BB               BBBBBBBBBBBBB",
"B 0  B         BB     BB               BBBBBBBBBBBBB",
"B B  B         BBBBBBBBB    BBBBBBBB   BBBBBBBBBBBBB",
"BGBGGBGGGGGGGGGBBBBBBBBBGGGGBBBBBBBBGGGBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
};
