# Общий мейкфайл

# Цель по умолчанию
all:
	$(MAKE) -C mySimpleComputer
	$(MAKE) -C console

run:
	cd console && ./pr01.exe
# Очистка временных файлов
clean:
	$(MAKE) -C mySimpleComputer clean
	$(MAKE) -C console clean
